Repository microsoft/ga4gh-tes, pull requests merged in 2024-07, with the labels that each got.

#715 WX-1594 Support for private ACR access in Terra
  src/CommonUtilities/Models/NodeTask.cs
  src/Tes.ApiClients.Tests/TerraApiStubData.cs
  src/Tes.ApiClients.Tests/TerraSamApiClientTests.cs
  src/Tes.ApiClients/HttpApiClient.cs
  src/Tes.ApiClients/Models/Terra/SamActionManagedIdentityApiResponse.cs
  src/Tes.ApiClients/TerraSamApiClient.cs
  src/Tes.Runner.Test/Docker/ContainerRegistryAuthorizationManagerTests.cs
  src/Tes.Runner.Test/Docker/DockerExecutorTests.cs
  src/Tes.Runner/Authentication/CredentialsManager.cs
  src/Tes.Runner/Docker/ContainerRegistryAuthorizationManager.cs
  src/TesApi.Tests/BatchSchedulerTests.cs
  src/TesApi.Tests/Runner/TaskToNodeTaskConverterTests.cs
  src/TesApi.Tests/StartupTests.cs
  src/TesApi.Tests/TerraActionIdentityProviderTests.cs
  src/TesApi.Tests/TerraApiStubData.cs
  src/TesApi.Tests/TestServices/TestServiceProvider.cs
  src/TesApi.Web/AzureProxy.cs
  src/TesApi.Web/BatchScheduler.cs
  src/TesApi.Web/CachingWithRetriesAzureProxy.cs
  src/TesApi.Web/DefaultActionIdentityProvider.cs
  src/TesApi.Web/IActionIdentityProvider.cs
  src/TesApi.Web/IAzureProxy.cs
  src/TesApi.Web/Management/Configuration/TerraOptions.cs
  src/TesApi.Web/Runner/NodeTaskBuilder.cs
  src/TesApi.Web/Runner/TaskExecutionScriptingManager.cs
  src/TesApi.Web/Runner/TaskToNodeTaskConverter.cs
  src/TesApi.Web/Startup.cs
  src/TesApi.Web/TerraActionIdentityProvider.cs
Labels: enhancement

#750 Fix failure to overwrite blobs
  src/TesApi.Web/AzureProxy.cs
Labels: bug, TES Priority: P1, Size: small

#758 Correct task input mapping
  src/TesApi.Web/Runner/TaskToNodeTaskConverter.cs
Labels: bug
